-- Code for creating person table --

-- get field sizes --
SELECT
    MAX(length(lastname))            lastname,
    MAX(length(firstname))           firstname,
    MAX(length(fullname) + 4)        fullname,
    MAX(length(gender))              gender
FROM
    x_person;
    
-- CREATE THE PERSON TABLE --
DROP TABLE person;

CREATE TABLE person (
    person_id       INTEGER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1000,
    lastname        VARCHAR2(40 CHAR),
    firstname       VARCHAR2(25 CHAR),
    middlename      VARCHAR2(3 CHAR),
    fullname        VARCHAR2(55 CHAR),
    dob             DATE,
    highest_degree  NUMBER,
    title           VARCHAR2(15 CHAR),
    gender          VARCHAR2(10 CHAR)
);

ALTER TABLE person ADD CONSTRAINT person_pk PRIMARY KEY ( person_id );

INSERT INTO person (
    lastname,
    firstname,
    middlename,
    dob,
    highest_degree,
    title,
    fullname,
    gender
)
    SELECT
        lastname,
        firstname,
        middlename,
        dob,
        highest_degree,
        title,
        title
        || ' '
        || firstname
        ||
        CASE
            WHEN middlename IS NOT NULL THEN
                    ' '
                    || middlename
                    || '. '
            ELSE
                ' '
        END
        || lastname fullname,
        gender
    FROM
        (
            SELECT
                p.lastname,
                p.firstname,
                TRIM(substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ                ', abs(mod(dbms_random.random, length('ABCDEFGHIJKLMNOPQRSTUVWXYZ                '))),
                            1))    middlename,
                dob,
                p.highest_degree,
                p.gender,
                CASE
                    WHEN p.highest_degree < 3 THEN
                            CASE p.gender
                                WHEN 'Female' THEN
                                    'Ms.'
                                ELSE
                                    'Mr.'
                            END
                    ELSE
                        'Dr.'
                END    title
            FROM
                x_person p
        )
    ORDER BY
        highest_degree DESC;
        
commit;

