CREATE TABLE course (
    course_id           INTEGER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1000,
    course_title        VARCHAR2(50 CHAR) NOT NULL,
    credits             INTEGER,
    course_level        INTEGER NOT NULL,
    person_person_id    INTEGER,
    start_date          DATE,
    end_date            DATE,
    faculty_faculty_id  INTEGER
);

INSERT INTO course (
    course_title,
    credits,
    course_level,
    faculty_faculty_id,
    start_date,
    end_date
)
    SELECT
        course,
        credits,
        course_level,
        faculty,
        '01-jan-2020'  start_date,
        '01-mar-2020'  end_date
    FROM
        (
            SELECT
                CASE round(dbms_random.value(1, 4))
                    WHEN 1  THEN
                        'Chemistry'
                    WHEN 2  THEN
                        'Physics'
                    WHEN 3  THEN
                        'Algebra'
                    WHEN 4  THEN
                        'Calculus'
                END                                            course,
                trunc(dbms_random.value(1, 5))                 credits,
                trunc(dbms_random.value(1, 5))                 course_level,
                trunc(dbms_random.value(1000, 5000))           faculty
            FROM
                faculty
            WHERE
                ROWNUM < 1000
        );

COMMIT;

MERGE INTO course
USING (
          SELECT
              c.course_id course_id,
              p.person_id
          FROM
                   (
                  SELECT
                      ROWNUM rn,
                      course_id
                  FROM
                      course c
              ) c
              JOIN (
                  SELECT
                      ROWNUM rn,
                      person_id
                  FROM
                      person p
                  WHERE
                          ROWNUM < 1000
                      AND highest_degree = 0
              ) p ON ( p.rn = c.rn )
      )
xx ON ( xx.course_id = course.course_id )
WHEN MATCHED THEN UPDATE
SET course.person_person_id = xx.person_id;

commit;