CREATE TABLE role (
    role_id     INTEGER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1000,
    role_name   VARCHAR2(25 CHAR),
    role_level  INTEGER,
    privileged  VARCHAR2(1 CHAR)
);


insert into role(role_name, role_level, privileged) values( 'STUDENT', 0, '' );
insert into role(role_name, role_level, privileged) values('TUTOR', 1, 'X' );
insert into role(role_name, role_level, privileged) values('LECTURER', 2,  'X' );
insert into role(role_name, role_level, privileged) values('PROFESSOR', 3, 'X');

select * from role;


drop table role;

COMMIT;

INSERT INTO role (
    role_level,
    privileged,
    role_type,
    new_role,
    person_person_id,
    faculty_faculty_id,
    active,
    eff_date
)
    SELECT
        '1',
        NULL,
        'S',
        NULL,
        p.person_id,
        c.faculty_faculty_id,
        'X',
        '01-jan-2020'
    FROM
             person p
        JOIN course c ON ( p.person_id = c.person_person_id );

COMMIT;

a course has: a professor/tutor/lecturer, a faculty, {students}