CREATE TABLE role (
    rolename            INTEGER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1000,
    role_level          INTEGER,
    privileged          VARCHAR2(1 CHAR),
    role_type           VARCHAR2(1 CHAR) NOT NULL,
    new_role            VARCHAR2(1),
    person_person_id    INTEGER,
    faculty_faculty_id  INTEGER,
    active              VARCHAR2(1),
    eff_date            DATE
);

COMMIT;

INSERT INTO role (
    role_level,
    privileged,
    role_type,
    new_role,
    person_person_id,
    faculty_faculty_id,
    active,
    eff_date
)
    SELECT
        '1',
        NULL,
        'S',
        NULL,
        p.person_id,
        c.faculty_faculty_id,
        'X',
        '01-jan-2020'
    FROM
             person p
        JOIN course c ON ( p.person_id = c.person_person_id );

COMMIT;