CREATE TABLE grades (
    grades_id         INTEGER
        GENERATED BY DEFAULT AS IDENTITY START WITH 1000,
    min               FLOAT,
    max               FLOAT,
    received_mark     FLOAT,
    representation    VARCHAR2(5 CHAR),
    passing_grade     FLOAT,
    person_person_id  INTEGER
);

COMMIT;

ALTER TABLE grades ADD CONSTRAINT grades_pk PRIMARY KEY ( grades_id ); 

insert into grades(min, max, received_mark, representation, passing_grade, person_person_id)
SELECT
minn,
maxx,
received_mark,
CASE received_mark
WHEN 2  THEN
'F'
WHEN 3  THEN
'C'
WHEN 4  THEN
'B'
WHEN 5  THEN
'A'
ELSE
'X'
END representation,
3,
z.person_id
FROM
(
SELECT
2                                        minn,
5                                        maxx,
trunc(dbms_random.value(2, 6))           received_mark,
3                                        passing_grade,
p.person_id
FROM
person p join course c on (p.person_id = c.person_person_id)
) z;

commit;