--------------------------------------------------------
--  File created - Tuesday-October-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COURSE_MASTER
--------------------------------------------------------

  CREATE TABLE "SYS"."COURSE_MASTER" 
   (	"COURSE_LEVEL" VARCHAR2(8 BYTE), 
	"COURSE_TITLE" CHAR(1 BYTE), 
	"CREDITS" NUMBER, 
	"START_DATE" VARCHAR2(10 BYTE), 
	"END_DATE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.COURSE_MASTER
SET DEFINE OFF;
Insert into SYS.COURSE_MASTER (COURSE_LEVEL,COURSE_TITLE,CREDITS,START_DATE,END_DATE) values ('Bachelor','1',5,'10-27-2020','04-27-2021');
Insert into SYS.COURSE_MASTER (COURSE_LEVEL,COURSE_TITLE,CREDITS,START_DATE,END_DATE) values ('Bachelor','2',5,'10-27-2020','04-27-2021');
Insert into SYS.COURSE_MASTER (COURSE_LEVEL,COURSE_TITLE,CREDITS,START_DATE,END_DATE) values ('Master','1',5,'10-27-2020','04-27-2021');
Insert into SYS.COURSE_MASTER (COURSE_LEVEL,COURSE_TITLE,CREDITS,START_DATE,END_DATE) values ('Master','2',5,'10-27-2020','04-27-2021');
Insert into SYS.COURSE_MASTER (COURSE_LEVEL,COURSE_TITLE,CREDITS,START_DATE,END_DATE) values ('Phd','1',5,'10-27-2020','04-27-2021');
Insert into SYS.COURSE_MASTER (COURSE_LEVEL,COURSE_TITLE,CREDITS,START_DATE,END_DATE) values ('Phd','2',5,'10-27-2020','04-27-2021');
